force-app/main/default/objects/Metadata_Type__mdt/Metadata_Type__mdt.object-meta.xml
<CustomObject>
    <description>Metadata types that are supported by on-platform sync processes.</description>
    <label>Metadata Type</label>
    <pluralLabel>Metadata Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Metadata_Type__mdt/fields/Batch_Size_Default__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size_Default__c</fullName>
    <description>Default batch size used to control the readMetadata() Soap api call.</description>
    <inlineHelpText>Default batch size used to control the readMetadata() Soap api call.</inlineHelpText>
    <label>Batch Size Default</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchLaunchREST.cls
@RestResource(urlMapping = '/batchLauncher')
global with sharing class BatchLaunchREST {
    class BatchLaunchException extends Exception {}

    @HttpPost
    // Returns the AsyncApexJob Id of the batch.
    // This implementation assumes that we're going to launch a single pre-defined batch.
    // This batch is then responsible for launching any additional batch jobs (chaining).
    global static String doPost() {
        Map<String, Metadata_Type__mdt> metadataTypes = Metadata_Type__mdt.getAll();
    
        // this may not be necessary, but like chicken soup, it can't hurt
        Auth.SessionManagement.setSessionLevel(Auth.SessionLevel.HIGH_ASSURANCE);
        
        List<String> sessionIdParts = UserInfo.getSessionId().split('!');
        String metadataType = 'Profile';
        Integer batchSize = Integer.valueOf(metadataTypes.get(metadataType).Batch_Size_Default__c);

        String result;
        try {
            result = Database.executeBatch(new GetMetadataXmlBatch(sessionIdParts, metadataType), batchSize);
        } catch (GetMetadataXmlBatch.MetadataXmlBatchException e) {
            // what do we return here??
        }

        return result;
    }
}