force-app/main/default/objects/Metadata_Item__c/Metadata_Item__c.object-meta.xml
<CustomObject>
    <description>Data related to specific metadata items processed by Elements on the Salesforce platform.</description>
    <label>Metadata Item</label>
    <nameField>
        <displayFormat>ITEM-{0000000}</displayFormat>
        <label>Metadata Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata_Item__c/fields/Encoded_FullName__c.field-meta.xml
<CustomField>
    <fullName>Encoded_FullName__c</fullName>
    <description>The URI-encoded fullName. Needed for the readMetadata() call.</description>
    <inlineHelpText>The URI-encoded fullName. Needed for the readMetadata() call.</inlineHelpText>
    <label>Encoded FullName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Item__c/fields/Metadata_Type__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Type__c</fullName>
    <description>The metadata item&apos;s metadata type.</description>
    <inlineHelpText>The metadata item&apos;s metadata type.</inlineHelpText>
    <label>Metadata Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Item__c/fields/Salesforce_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Id__c</fullName>
    <description>The item&apos;s Salesforce Id.</description>
    <inlineHelpText>The item&apos;s Salesforce Id.</inlineHelpText>
    <label>Salesforce Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MetadataXmlBatchHelperTest.cls
@isTest
public class MetadataXmlBatchHelperTest {
    @TestSetup
    static void makeData(){
        Metadata_Item__c item = new Metadata_Item__c();
            item.Metadata_Type__c = 'Profile';
            item.Encoded_FullName__c = 'test';
            item.Salesforce_Id__c = '000000000000000AAA';
            item.Is_Deleted__c = false;
            item.Is_Too_Large_To_Process__c = false;        
        insert item;
    }

    @isTest
    private static void testConstructor() {
        String sessionId = 'test';
        String metadataType = 'Profile';
        MetadataXmlBatchHelper helper = new MetadataXmlBatchHelper(sessionId, metadataType);
    }

    @isTest
    private static void testUpdateSavedMetadataItems() {
        MetadataXmlBatchHelper.MetadataItemWrapper item = new MetadataXmlBatchHelper.MetadataItemWrapper();
        item.encodedFullName = 'test';
        item.lastSavedDatetime = Datetime.now();
        item.hash = 12345;
        MetadataXmlBatchHelper.updateSavedMetadataItems('Profile', new Map<String, MetadataXmlBatchHelper.MetadataItemWrapper>{ 'test' => item });
    }
}